config/routes.rb
Rails.application.routes.draw do
  get root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, except: [:destroy, :update, :edit] do
    resources :reviews, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
   has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian']}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] },
                     numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
  end
  end

   def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category )
   end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
  end
end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> -->


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "resto.png", height: 50  %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

  </div>
  </div>


<div class="container">
  <h2>Restaurants</h2>
<%= link_to "Create a new restaurant", new_restaurant_path(@restaurant)  %>
  <% @restaurants.each do |r| %>
    <h3><%=link_to r.name, restaurant_path(r) %></h3>

  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container col-md-3 ">
<%= simple_form_for(@restaurant) do |f| %>
<%=f.input :name%>
<%=f.input :address%>
<%=f.input :phone_number%>
<%=f.input :category, collection:['chinese', 'italian', 'japanese', 'french', 'belgian']%>
<%=f.submit class: "btn btn-primary"%>

<% end %>
<div>

app/views/restaurants/show.html.erb
<div class="container">
<h2><%=@restaurant.name%></h2>
<p><%= "#{@restaurant.address},#{@restaurant.phone_number}. Category :#{@restaurant.category}" %></p>


  <% @restaurant.reviews.each do |review| %>
    <p><%= review.rating %></p>
    <p><%= review.content %></p>
  <% end %>
<p><%= link_to "Add new review",new_restaurant_review_path(@restaurant) %></p>
<p><%= link_to "Go back", root_path %></p>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container col-md-3">
<%= simple_form_for([@restaurant, @review]) do |f| %>
<%= f.input :rating, collection:[ 0,1,2,3,4,5 ] %>
<%= f.input :content %>
<%= f.submit class: "btn btn-primary" %>

<% end %>
</div>